### ISSUE TITLE
Allow to define custom project main file

### ISSUE THREAD

**Issue by jamofer** [jorsanpe/cpm#104]
## Description
`main.cpp` is harcoded as source file:
https://github.com/jorsanpe/cpm/blob/312c6da74803d62ca53b863e6932029d07289fb9/cpm/domain/project_loader.py#L14-L19

## Proposal
Instead of forcing to write a dummy `main.cpp` even your project is C code I suggest to allow to the user something like this in the `project.yaml` file:
```
name: 'c-dummy'
description: 'Dummy C project'
main: 'app/main.c' # <- by default main.cpp
packages:
  api:
plugins:
  cest: '1.0'
link_options:
  libraries: ['libfyaml']
```

Or maybe just try with `main.cpp` and then fallback to `main.c`.

What do you think?

**Comment by jorsanpe** [comment]
This issue is related to #38.

**Comment by jorsanpe** [comment]
I'm going to refactor the selection of the `main.c` file. Instead of forcing the user to define a main file, in order to support multiple targets as in #183, the `main` function should be provided by a user package. With the new project schema, the way to do this should be:

```yaml
targets:
   default:
    packages:
      targets/main:
```

This configuration would work, assuming that there is a package `targets/main` containing a source code file with the implementation of `main`.

The reason for doing this is that some programs would not produce an executable binary, but rather a library. Or, for example, the project could depend on a runtime (like aws-lambda) that would be the one to provide the main function.
