### ISSUE TITLE
Allow users to build the code from inside a container

### ISSUE THREAD

**Issue by jorsanpe** [jorsanpe/cpm#122]
`cpm` could offer seamless integration with containers (e.g. docker), so that if the project is properly configured, it will build the project making use of containers and not using the host build tools.

```
# project.yaml

project_name: 'project'
targets:
    rpi4:
        image: cpmbits/raspberrypi4:64
```

With the above description, when running `cpm build rpi4`, cpm would use the configuration available in the project descriptor. If that configuration is not found, it would try to find the image in the cpmbits docker hub.
