### ISSUE TITLE
Libraries and bits should be child of a dependencies element in the project descriptor

### ISSUE THREAD

**Issue by jorsanpe** [jorsanpe/cpm#133]
The current project descriptor schema is a bit gcc centric. Maybe, it would be better to describe the dependencies under the same umbrella:

```
dependencies:
  bits:
    cest: '1.0'
  libraries: ['boost_filesystem']
```
