### ISSUE TITLE
Allow default compilation to be run from a specific docker container

### ISSUE THREAD

**Issue by jorsanpe** [jorsanpe/cpm#160]
The user could be allowed to configure the default docker image in the project descriptor, maybe by configuring the `default` target.

```yaml
# project.yaml
name: 'Project'
targets:
    default:
        image: `docker/image`
```

This would allow for simpler project and tool setup and compilation among team developers.
