### ISSUE TITLE
Implement project descriptor schema version2

### ISSUE THREAD

**Issue by jorsanpe** [jorsanpe/cpm#167]
After the initial version, this version should allow for cleaner project specification. It should also allow to have a single loader for both bits and projects.

```yaml
name: 'cpm-hub'
description: 'CPM Hub open source server for hosting CPM software'
build:
    packages:
        cpm-hub/http:
        cpm-hub/infrastructure:
        cpm-hub/management:
        cpm-hub/bits:
        cpm-hub/users:
        cpm-hub/authentication:
        cpm-hub/logging:
        cpm-hub/kpi:
        cpm-hub/database:
    cflags: []
    cppflags: ['-std=c++11', '-g']
    ldflags: []
    libraries: [ 'boost_filesystem', 'boost_system', 'boost_program_options', 'pthread', 'ssl', 'crypto' ]
    bits:
        mongoose: '6.16'
        json: '3.7.3'
        base64: '1.0'
        blake3: '1.0'
        inih: '1.0'
        spdlog: '1.6.1'
        sqlite3: '3.32.3'
    targets:
        default:
            image: 'docker/image'
        rpi4:
            image: 'cpmbits/raspberrypi4:64'
            packages:
                cpm-hub/rpi4:
test:
    packages:
        tests/mocks:
    bits:
        fakeit: '2.0.5'
        cest: '1.0'
    compile_flags: ['-O0']
    link_options:
        libraries: ['CppUTest', 'CppUTestExt']
actions:
    docker: 'docker run -it -v $(pwd):/project -w /project jorsanpe/cpm'
```
