### ISSUE TITLE
Make cpm script OS independent

### ISSUE THREAD

**Issue by jamofer** [jorsanpe/cpm#169]
According to [this](https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html), cpm script shall be defined as a console entry. With the current `setup.cfg` it will not be OS independent (IE: in windows it needs to be wrapped into an exe file).

# Proposal
To change this line:
https://github.com/jorsanpe/cpm/blob/befcaca7b49b0911f2897498a041d773d40018a8/setup.cfg#L20
With this:
```toml
[options.entry_points]
console_scripts =
    cpm = :main
```

We have to take account about `cpm = :main` means the function `main` inside `cpm`.
