### ISSUE TITLE
Allow configuring bit compilation options

### ISSUE THREAD

**Issue by jorsanpe** [jorsanpe/cpm#238]
Many libraries offer compile-time options through macros. The way cpm builds the project right now does not allow setting those flags. The bits model could be extended to allow fine grained control over bit compilation.

For example:
```yaml
build:
  bits:
    mongoose:
      version: '6.16'
      build:
        cflags: ['-DMG_ENABLE_GETADDRINFO']
```
