### ISSUE TITLE
Allow reading compilation flags and preprocessor defines from file

### ISSUE THREAD

**Issue by jorsanpe** [jorsanpe/cpm#260]
When a project has a long list of compilation options or preprocessor defines, the `project.yaml` file can get too bloated and be barely readable. Separating all the preprocessor defines in different files would be a good solution. Probably, the best way to do this is to allow including content from other yaml files, in the same way as swagger allows loading yaml trees from other files:

```yaml
# project.yaml
build:
  cflags:
    $ref: 'cflags.yaml'
```

```yaml
# cflags.yaml
- '-std=c++11'
- '-g'
```
