### ISSUE TITLE
Allow recursive/non recursive packages

### ISSUE THREAD

**Issue by jorsanpe** [jorsanpe/cpm#263]
Consider the support for recursive and non recursive packages. For example, if packages are declared recursively:

```
package:
  parent:
    cflags: [ 'parent-flag' ]
  parent/child:
    cflags: [ 'child-flag' ]
```

I think it would make sense that the child package inherited the cflags from the parent package.
