### ISSUE TITLE
Allow the user to extend CPM actions via scripts in project.yaml

### ISSUE THREAD

**Issue by jorsanpe** [jorsanpe/cpm#45]
A scripts section would allow the user to create custom actions:

```yaml
project: MyProject
actions:
    deploy: "scp files user@destination:"
```

And then, this action could be run as:

```cpm deploy```
